services:
  web:
    build:
      context: ./node-app
    ports:
      - "3000:80"
    depends_on:
      - python-api

  redis:
    image: redis:7-alpine

  python-api:
    build:
      context: ./py-app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  python-worker:
    build:
      context: ./py-app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: ["celery", "-A", "app.celery_app:celery_app", "worker", "--loglevel=INFO"]


